#!/usr/bin/env python3
"""make_zip.py -- package the Oai source tree into a single zip.

This is the archive you hand to somebody who wants to build it themselves: all
the sources, headers, scripts, tests, the corpus and the documentation, and
nothing that was generated by a build.

    python3 tools/make_zip.py                  -> dist/Oai-1.0.0-src.zip
    python3 tools/make_zip.py --out /tmp/x.zip
    python3 tools/make_zip.py --list           print what would go in

Part of Oai. SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import argparse
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"

# Directories and patterns that never belong in a source archive.
SKIP_DIRS = {"build", "dist", "bin", ".git", "__pycache__", ".vscode",
             ".idea", "node_modules"}
SKIP_SUFFIXES = {".o", ".obj", ".exe", ".bin", ".tmp", ".pyc", ".zip",
                 ".log", ".dSYM"}
SKIP_NAMES = {".DS_Store", "oai-checkpoint.bin", "oai.conf"}


def read_version() -> str:
    header = (ROOT / "include" / "oai.h").read_text(encoding="utf-8")
    for line in header.splitlines():
        if "OAI_VERSION_STRING" in line and '"' in line:
            return line.split('"')[1]
    return "0.0.0"


def should_include(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if any(part in SKIP_DIRS for part in rel.parts):
        return False
    if path.name in SKIP_NAMES:
        return False
    if path.suffix in SKIP_SUFFIXES:
        return False
    return path.is_file()


def collect() -> list[Path]:
    return sorted(p for p in ROOT.rglob("*") if should_include(p))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__)
    ap.add_argument("--out", type=Path, default=None,
                    help="where to write the archive")
    ap.add_argument("--list", action="store_true",
                    help="print the file list and exit")
    opts = ap.parse_args()

    files = collect()
    if opts.list:
        for f in files:
            print(f.relative_to(ROOT))
        print(f"\n{len(files)} files")
        return 0

    version = read_version()
    out = opts.out or (DIST / f"Oai-{version}-src.zip")
    out.parent.mkdir(parents=True, exist_ok=True)
    root_name = f"Oai-{version}"

    total = 0
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for f in files:
            z.write(f, f"{root_name}/{f.relative_to(ROOT)}")
            total += f.stat().st_size

    size = out.stat().st_size
    print(f"wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}")
    print(f"  {len(files)} files, {total/1024:.0f} KB -> {size/1024:.0f} KB "
          f"({100*size/total:.0f}%)")
    print(f"  unpacks into {root_name}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
