# Tuned for zram swap (see /etc/systemd/zram-generator.conf.d/horizon.conf)
vm.swappiness = 100
vm.page-cluster = 0
# Bigger inotify limits for IDEs, file sync and Baloo file search
fs.inotify.max_user_watches = 524288
