# @DISTRO_NAME@ installer (Calamares) — module sequence.
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: kerncopy
  module: shellprocess
  config: shellprocess_kerncopy.conf
- id: bootloader_packages
  module: contextualprocess
  config: bootloader_packages.conf
- id: cleanup
  module: shellprocess
  config: shellprocess_cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - shellprocess@kerncopy
  - contextualprocess@bootloader_packages
  - packages
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: horizon
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
