#!/usr/bin/env bash
# Generate the Horizon GRUB theme (graphical boot menu) into <outdir>.
# Only JPEG images are used: the Secure Boot-signed GRUB has jpeg built in, but not png.
# Usage: make-grub-theme.sh <outdir> <distro name> <assets dir>
set -euo pipefail
out="$1" name="$2" assets="$3"
mkdir -p "$out"

font_file() { # font_file <style>  -> path to an Inter (or fallback) font file
    local f
    f=$(fc-match -f '%{file}' "Inter:style=$1" 2>/dev/null || true)
    [[ -n $f && -e $f ]] || f=$(fc-match -f '%{file}' "DejaVu Sans:style=$1" 2>/dev/null || true)
    [[ -n $f && -e $f ]] || { echo "no usable font found (install fonts-inter)" >&2; exit 1; }
    echo "$f"
}
regular=$(font_file Regular)
bold=$(font_file Bold)
# -n fixes the family name, so theme.txt can reference "Horizon Regular 20" etc.
grub-mkfont -n Horizon -s 16 -o "$out/horizon-regular-16.pf2" "$regular" 2>/dev/null
grub-mkfont -n Horizon -s 20 -o "$out/horizon-regular-20.pf2" "$regular" 2>/dev/null
grub-mkfont -n Horizon -s 22 -o "$out/horizon-bold-22.pf2"    "$bold" 2>/dev/null
grub-mkfont -n Horizon -s 36 -o "$out/horizon-bold-36.pf2"    "$bold" 2>/dev/null

rsvg-convert -w 1920 -h 1080 "$assets/wallpaper-dark.svg" -o "$out/bg.png"
convert "$out/bg.png" -quality 90 "$out/background.jpg"
# JPEG has no transparency: put the logo on the background colour found under it.
under=$(convert "$out/bg.png" -crop 96x96+912+119 -resize 1x1\! -format '#%[hex:p{0,0}]' info:)
rsvg-convert -w 96 -h 96 "$assets/logo.svg" -o "$out/logo.png"
convert "$out/logo.png" -background "${under:0:7}" -flatten -quality 95 "$out/logo.jpg"
rm "$out/bg.png" "$out/logo.png"

# Selection highlight: a 9-part box, all parts a solid colour.
for part in nw n ne w c e sw s se; do
    convert -size 8x8 "xc:#6b5bd6" -quality 95 "$out/select_$part.jpg"
done

cat > "$out/theme.txt" <<THEME
# Horizon boot menu theme (generated by scripts/make-grub-theme.sh)
title-text: ""
desktop-image: "background.jpg"
desktop-image-scale-method: "crop"
desktop-color: "#1d1b4b"
terminal-font: "Horizon Regular 16"
terminal-left: "10%"
terminal-top: "20%"
terminal-width: "80%"
terminal-height: "60%"
terminal-box: "select_*.jpg"

+ image {
    left = 50%-48
    top = 11%
    width = 96
    height = 96
    file = "logo.jpg"
}
+ label {
    left = 0
    top = 11%+110
    width = 100%
    align = "center"
    text = "$name"
    font = "Horizon Bold 36"
    color = "#ffffff"
}
+ boot_menu {
    left = 30%
    top = 38%
    width = 40%
    height = 42%
    item_font = "Horizon Regular 20"
    selected_item_font = "Horizon Bold 22"
    item_color = "#c9c6ee"
    selected_item_color = "#ffffff"
    item_height = 40
    item_padding = 14
    item_spacing = 6
    icon_width = 0
    icon_height = 0
    item_icon_space = 0
    selected_item_pixmap_style = "select_*.jpg"
    scrollbar = false
}
+ label {
    id = "__timeout__"
    left = 0
    top = 84%
    width = 100%
    align = "center"
    font = "Horizon Regular 16"
    color = "#a9a6d6"
    text = "Starting automatically in %d seconds"
}
+ label {
    left = 0
    top = 90%
    width = 100%
    align = "center"
    font = "Horizon Regular 16"
    color = "#8784b8"
    text = "↑ ↓ choose    Enter start    E edit    C command line"
}
THEME
