---
overwrite: false
keepDistributor: false
prefer_grub_d: true
defaults:
    GRUB_TIMEOUT: 3
    GRUB_TIMEOUT_STYLE: "hidden"
    GRUB_ENABLE_CRYPTODISK: true
    GRUB_DISABLE_OS_PROBER: false
always_use_defaults: true
