---
overwrite: false
keepDistributor: false
prefer_grub_d: true
defaults:
    # Show the themed boot menu briefly (hide it with: horizon boot menu off)
    GRUB_TIMEOUT: 3
    GRUB_TIMEOUT_STYLE: "menu"
    GRUB_ENABLE_CRYPTODISK: true
    GRUB_DISABLE_OS_PROBER: false
always_use_defaults: true
