# Remove the live-session-only packages from the installed system.
---
backend: apt
update_db: false
skip_if_no_internet: false
operations:
    - remove:
        - horizon-installer
        - calamares
        - casper
    - try_install:
        - language-pack-$LOCALE
        - language-pack-kde-$LOCALE
        - hunspell-$LOCALE
