---
# UEFI: 1 GiB EFI system partition (room for firmware updates and extra kernels).
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 1024MiB
    minimumSize: 300MiB
    label: "EFI"
enableLuksAutomatedPartitioning: true
luksGeneration: luks2
userSwapChoices:
    - none
    - file
initialSwapChoice: file
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
partitionLayout:
    - name: "@DISTRO_ID@_boot"
      filesystem: ext4
      noEncrypt: true
      onlyPresentWithEncryption: true
      mountPoint: "/boot"
      size: 2G
    - name: "@DISTRO_ID@_root"
      filesystem: unknown
      mountPoint: "/"
      size: 100%
