---
defaultGroups:
    - adm
    - cdrom
    - dip
    - lpadmin
    - plugdev
    - sudo
    - name: sambashare
      must_exist: false
      system: true
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: false
passwordRequirements:
    minLength: 6
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
    shell: /bin/bash
    forbidden_names: [ root, daemon, bin, sys, sync, games, man, lp, mail, news, uucp, proxy,
                       www-data, backup, list, irc, apt, nobody, messagebus, syslog, sddm,
                       polkitd, rtkit, colord, avahi ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "${first}-${product}"
    forbidden_names: [ localhost ]
