---
showSupportUrl:      true
showKnownIssuesUrl:  false
showReleaseNotesUrl: true
requirements:
    requiredStorage: 20
    requiredRam:     2.0
    internetCheckUrl: http://connectivity-check.ubuntu.com
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
geoip:
    style:    "xml"
    url:      "https://geoip.ubuntu.com/lookup"
    selector: "CountryCode"
